### ISSUE TITLE
Play button does not work in Firefox

### ISSUE THREAD

**Issue by bdwyer2** [IBM/MAX-Audio-Sample-Generator#1]
The play button seems to work in Google Chrome but not Firefox
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/19673623/45787147-9cca0880-bc28-11e8-88e4-226538372cff.png">

**Comment by xuhdev** [comment]
librosa/librosa#361 seems to be relevant here. In short, this model is outputting PCM wav files with 32 bit depth, but [Firefox only supports 8 or 16 bits](https://support.mozilla.org/en-US/kb/html5-audio-and-video-firefox#w_supported-formats).

[This comment](https://github.com/librosa/librosa/issues/361#issuecomment-219874390) gives a quick solution, but I haven't really double checked. IMO a more reliable way is to directly use the [underlying scipy function](https://docs.scipy.org/doc/scipy/reference/generated/scipy.io.wavfile.write.html) (whose doc clearly states that numpy datatype needs to be int16 to output 16 bit PCM wav files) and drop librosa as a dependency (which depends on scipy anyway).
