### ISSUE TITLE
Avoid disk writing for generated wave files

### ISSUE THREAD

**Issue by xuhdev** [IBM/MAX-Audio-Sample-Generator#16]
This line write a wave file to a constant file name:
https://github.com/IBM/MAX-Audio-Sample-Generator/blob/0615b4ee7d506799bc3a1fb8f7e76bceb5b72346/core/model.py#L50

This may cause race condition and is not so efficient.

**Comment by bdwyer2** [comment]
We fixed this issue for another model. I will try to find which one and do the same here.
